### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by spiderdev86** [aksonov/react-native-tableview#202] opened 2019-05-23 21:23 UTC
Cannot read property 'Constants' of undefined

```
package.json

...
"react": "16.6.1",
 "react-native": "0.57.7",
"react-native-tableview": "^2.5.0",
....
```

`yarn install`
`react-native run-ios` or `react-native run-android`

I am facing "Cannot read property 'Constants' of undefined"

![Screen Shot 2019-05-23 at 2 21 18 PM](https://user-images.githubusercontent.com/8231275/58287517-0d9c6400-7d66-11e9-9661-5ec377829208.png)

Does anyone know the solution of this problem?
Thanks

**Comment by MobileDev418** [comment] 2019-05-24 02:41
I am facing same issue

**Comment by iRoachie** [comment] 2019-05-31 10:53
Duplicate of #194

**Closed by iRoachie** 2019-05-31 10:53 UTC
