### ISSUE TITLE
Support for Custom Accessory Views

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#28] opened 2015-10-27 21:40 UTC
See [`accessoryView`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewCell_Class/index.html#//apple_ref/occ/instm/UITableViewCell/accessoryView) and [broadly](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewCell_Class/index.html#//apple_ref/occ/instm/UITableViewCell/accessoryView).

**Comment by aksonov** [comment] 2015-10-28 06:54
It seems duplicate of #21

**Closed by aksonov** 2015-10-28 06:54 UTC
Labels: enhancement, help wanted
